# Generated by Django 6.0.5 on 2026-05-29 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHumor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('nivel_ansiedade', models.PositiveSmallIntegerField(help_text='Nível de ansiedade de 1 a 10.')),
                ('humor_emoji', models.PositiveSmallIntegerField(choices=[(1, 'Normal'), (2, 'Triste'), (3, 'Feliz'), (4, 'Esperançoso'), (5, 'Raivoso'), (6, 'Apaixonado'), (7, 'Preocupado'), (8, 'Ansioso'), (9, 'Entediado')], help_text='Humor representado por um emoji (1 a 9).')),
                ('texto_livre', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_humor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Humor',
                'verbose_name_plural': 'Registros de Humor',
                'ordering': ['-data_hora'],
                'constraints': [models.CheckConstraint(condition=models.Q(('nivel_ansiedade__gte', 1), ('nivel_ansiedade__lte', 10)), name='nivel_ansiedade_entre_1_e_10'), models.CheckConstraint(condition=models.Q(('humor_emoji__gte', 1), ('humor_emoji__lte', 9)), name='humor_emoji_entre_1_e_9')],
            },
        ),
    ]
